#pragma once

#define ACUL_PATH_SEPARATOR_WIN32 '\\'
#define ACUL_PATH_SEPARATOR_UNIX  '/'

#ifdef _WIN32
    #define ACUL_PATH_SEPARATOR ACUL_PATH_SEPARATOR_WIN32
#else
    #define ACUL_PATH_SEPARATOR ACUL_PATH_SEPARATOR_UNIX
#endif

#define ACUL_IS_PATH_SEPARATOR(c) (c == ACUL_PATH_SEPARATOR_WIN32 || c == ACUL_PATH_SEPARATOR_UNIX)